# **Manual Convolution**
---
The following project show examples of a manual convolution where a filter (kernel) is applied across the values of an array (ex. image).

Author: Pedro Zuñiga

In [105]:
# Import libraries
import numpy as np

In [106]:
def convolution(image, kernel):
  result = []
  multip_res = []
  img_len = len(image)
  kernel_len = len(kernel)
  x = img_len - kernel_len
  for i in range(0, img_len-x):
    result.append([])                                                                   # Create new empty array inside the list
    multip_res.append([])
    for j in range(0, img_len-x):
      print(f'Row {i+1}, Column {j+1}')
      print('Kernel')
      print(kernel)
      print('Part of the image affected by the kernel')
      print(image[i:i+kernel_len, j:j+kernel_len])
      multiplication = (np.multiply(kernel, image[i:i+kernel_len, j:j+kernel_len]))     # Element-wise multiplication
      print('Multiplication')
      print(multiplication)
      print('----------------------------------------')
      multip_res[i].append(multiplication)
      result[i].append(multiplication.sum())                                            # Sum the multiplication results
  print('List of multiplications')
  print(np.array(multip_res))
  print('\nFinal Result (Feature Map)')
  print(np.array(result))

In [115]:
image1 = np.array([[1,2,-1],[1,2,-1],[-1,-2,-1]])
print('Image\n', image1)
print('Image lenght\n', len(image1))

Image
 [[ 1  2 -1]
 [ 1  2 -1]
 [-1 -2 -1]]
Image lenght
 3


In [108]:
kernel1 = np.array([[1,2],[1,2]])
print("Kernel\n", kernel1)
print('Kernel lenght\n', len(kernel1))

Kernel
 [[1 2]
 [1 2]]
Kernel lenght
 2


In [109]:
convolution(image1, kernel1)

Row 1, Column 1
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[1 2]
 [1 2]]
Multiplication
[[1 4]
 [1 4]]
----------------------------------------
Row 1, Column 2
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[ 2 -1]
 [ 2 -1]]
Multiplication
[[ 2 -2]
 [ 2 -2]]
----------------------------------------
Row 2, Column 1
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[ 1  2]
 [-1 -2]]
Multiplication
[[ 1  4]
 [-1 -4]]
----------------------------------------
Row 2, Column 2
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[ 2 -1]
 [-2 -1]]
Multiplication
[[ 2 -2]
 [-2 -2]]
----------------------------------------
List of multiplications
[[[[ 1  4]
   [ 1  4]]

  [[ 2 -2]
   [ 2 -2]]]


 [[[ 1  4]
   [-1 -4]]

  [[ 2 -2]
   [-2 -2]]]]

Final Result (Feature Map)
[[10  0]
 [ 0 -4]]


In [110]:
image2 = np.array([[3,8,-5,2,-2],[-1,-2,1,-5,-7],[9,-6,4,-3,-6],[-3,-1,-2,1,2],[8,8,3,-7,1]])
print("Image 2\n", image2)
print('Image 2 lenght\n', len(image2))

Image 2
 [[ 3  8 -5  2 -2]
 [-1 -2  1 -5 -7]
 [ 9 -6  4 -3 -6]
 [-3 -1 -2  1  2]
 [ 8  8  3 -7  1]]
Image 2 lenght
 5


In [111]:
kernel2 = np.array([[1,2,1],[1,2,-1],[-1,1,-1]])
print("Kernel 2\n", kernel2)
print('Kernel 2 lenght\n', len(kernel2))

Kernel 2
 [[ 1  2  1]
 [ 1  2 -1]
 [-1  1 -1]]
Kernel 2 lenght
 3


In [112]:
convolution(image2, kernel2)

Row 1, Column 1
Kernel
[[ 1  2  1]
 [ 1  2 -1]
 [-1  1 -1]]
Part of the image affected by the kernel
[[ 3  8 -5]
 [-1 -2  1]
 [ 9 -6  4]]
Multiplication
[[ 3 16 -5]
 [-1 -4 -1]
 [-9 -6 -4]]
----------------------------------------
Row 1, Column 2
Kernel
[[ 1  2  1]
 [ 1  2 -1]
 [-1  1 -1]]
Part of the image affected by the kernel
[[ 8 -5  2]
 [-2  1 -5]
 [-6  4 -3]]
Multiplication
[[  8 -10   2]
 [ -2   2   5]
 [  6   4   3]]
----------------------------------------
Row 1, Column 3
Kernel
[[ 1  2  1]
 [ 1  2 -1]
 [-1  1 -1]]
Part of the image affected by the kernel
[[-5  2 -2]
 [ 1 -5 -7]
 [ 4 -3 -6]]
Multiplication
[[ -5   4  -2]
 [  1 -10   7]
 [ -4  -3   6]]
----------------------------------------
Row 2, Column 1
Kernel
[[ 1  2  1]
 [ 1  2 -1]
 [-1  1 -1]]
Part of the image affected by the kernel
[[-1 -2  1]
 [ 9 -6  4]
 [-3 -1 -2]]
Multiplication
[[ -1  -4   1]
 [  9 -12  -4]
 [  3  -1   2]]
----------------------------------------
Row 2, Column 2
Kernel
[[ 1  2  1]
 [ 1  2 -1]
 [

In [113]:
convolution(image2, kernel1)

Row 1, Column 1
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[ 3  8]
 [-1 -2]]
Multiplication
[[ 3 16]
 [-1 -4]]
----------------------------------------
Row 1, Column 2
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[ 8 -5]
 [-2  1]]
Multiplication
[[  8 -10]
 [ -2   2]]
----------------------------------------
Row 2, Column 1
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[-1 -2]
 [ 9 -6]]
Multiplication
[[ -1  -4]
 [  9 -12]]
----------------------------------------
Row 2, Column 2
Kernel
[[1 2]
 [1 2]]
Part of the image affected by the kernel
[[-2  1]
 [-6  4]]
Multiplication
[[-2  2]
 [-6  8]]
----------------------------------------
List of multiplications
[[[[  3  16]
   [ -1  -4]]

  [[  8 -10]
   [ -2   2]]]


 [[[ -1  -4]
   [  9 -12]]

  [[ -2   2]
   [ -6   8]]]]

Final Result (Feature Map)
[[14 -2]
 [-8  2]]
